- name: Backup Huawei USG6305E Configuration
  hosts: usg6305e
  gather_facts: no

  vars:
    backup_dir: "/backups/huawei"
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"
    filename: "usg6305e_{{ inventory_hostname }}_{{ timestamp }}.cfg"

  tasks:

    - name: Ensure backup directory exists
      delegate_to: localhost
      run_once: true
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'

    - name: Execute display current-configuration
      ansible.netcommon.cli_command:
        command: display current-configuration
      register: config_output

    - name: Save configuration to file
      copy:
        content: "{{ config_output.stdout }}"
        dest: "{{ backup_dir }}/{{ filename }}"
      delegate_to: localhost

